version: '3'

services:
    server:
      image: bielr/util-aligner-server
      depends_on:
        - rabbitmq
        - mysql
        - mongo
      volumes:
        - .:/opt/:rw
      networks:
        - server-net
        - util-net

    mysql:
      image: mysql:5.7.17
      ports:
        - 3308:3306
      command:
        - --character-set-server=utf8
        - --collation-server=utf8_unicode_ci
        - --skip-character-set-client-handshake
      volumes:
        - mysql-data:/var/lib/mysql
        - ./dumps:/opt/dumps
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=protein_db
        - MYSQL_USER=puser
        - MYSQL_PASSWORD=puser
      networks:
        - util-net
        - server-net

    rabbitmq:
      image: rabbitmq:3-management-alpine
      ports:
        - 15672:15672
      networks:
        - util-net
        - server-net
    
    mongo:
      image: mongo:latest
      command: ['mongod', '--storageEngine=mmapv1']
      volumes:
        - mongo-data:/data/db
      networks:
        - util-net
        - server-net


volumes:
  mysql-data: {}
  mongo-data: {}

networks:
  server-net: {}
  util-net:
    external: true